name: NuGet Publish

on:
  push:
    branches:
      - master

    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' # Replace with the desired .NET 7 version

      - name: Get Package Version from .csproj
        id: version
        run: |
          PACKAGE_VERSION=$(cat KuveytTurkSignatureGenerator.csproj | grep -oPm1 "(?<=<Version>)[^<]+")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "Package Version: $PACKAGE_VERSION"
        shell: bash

      - name: Build and Publish NuGet package
        run: |
          dotnet build -c Release
          dotnet pack -c Release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: '**/*.nupkg'
          name: Release ${{ env.PACKAGE_VERSION }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NuGet Package
        run: |
          nugetApiKey=$NUGET_API_KEY
          nugetPackage=${{ steps.create_release.outputs.assets }}
          dotnet nuget push $nugetPackage -k $nugetApiKey -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}